[[MsQUIC]]
arch = "aarch64"
git-tree-sha1 = "b6bab1b50472efeb71e4ccf3a60e219fb7e6cae3"
os = "macos"

    [[MsQUIC.download]]
    sha256 = "99e3462a3a21181c3015800f97b99ed9fc0430f4d9a98e994f5b74bafe5d4571"
    url = "https://github.com/InnateSystems/MsQUIC/releases/download/v0.0.0-alpha/msquic.v2.4.8.aarch64-apple-darwin.tar.gz"
